DROP SCHEMA IF EXISTS testdb;

CREATE SCHEMA testdb;

USE testdb;

CREATE TABLE PERSON(
ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
FIRST_NAME VARCHAR(40) NOT NULL,
LAST_NAME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(60) NOT NULL UNIQUE,
BIRTH_DATE DATE NOT NULL,
REGISTRATION_DATE DATETIME DEFAULT now(),
CITY VARCHAR(80),
IS_ACTIVE TINYINT DEFAULT false
);

CREATE TABLE TASK(
ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
TITLE VARCHAR(255) NOT NULL,
DESCRIPTION VARCHAR(400),
PERSON_ID INT,

FOREIGN KEY (PERSON_ID) REFERENCES PERSON(ID)
);

CREATE TABLE GROUP_(
ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
GROUP_NAME VARCHAR(255) NOT NULL
);


CREATE TABLE PERSON_GROUP(
ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
PERSON_ID INT NOT NULL,
GROUP_ID INT NOT NULL,

FOREIGN KEY (PERSON_ID) REFERENCES PERSON(ID),
FOREIGN KEY (GROUP_ID) REFERENCES GROUP_(ID)
);